-- MySQL Script generated by MySQL Workbench
-- Thu Mar 11 00:40:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Texts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Texts` (
  `idTexts` INT NOT NULL AUTO_INCREMENT,
  `short_text` MEDIUMTEXT NULL,
  `text` LONGTEXT NULL,
  PRIMARY KEY (`idTexts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles` (
  `idArticles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `image` VARCHAR(200) NULL,
  `url` VARCHAR(200) NOT NULL,
  `Texts_idTexts` INT NOT NULL,
  `Authors_id` INT NOT NULL,
  `Sections_id` INT NOT NULL,
  PRIMARY KEY (`idArticles`, `url`, `Texts_idTexts`, `Authors_id`, `Sections_id`),
  INDEX `fk_Articles_Texts1_idx` (`Texts_idTexts` ASC) VISIBLE,
  INDEX `fk_Articles_Authors1_idx` (`Authors_id` ASC) VISIBLE,
  INDEX `fk_Articles_Sections1_idx` (`Sections_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Texts1`
    FOREIGN KEY (`Texts_idTexts`)
    REFERENCES `mydb`.`Texts` (`idTexts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `mydb`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Sections1`
    FOREIGN KEY (`Sections_id`)
    REFERENCES `mydb`.`Sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Articles` (
  `Articles_idArticles` INT NOT NULL,
  `Articles_url` VARCHAR(200) NOT NULL,
  `Articles_idArticles1` INT NOT NULL,
  `Articles_url1` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `Articles_url`, `Articles_idArticles1`, `Articles_url1`),
  INDEX `fk_Articles_has_Articles_Articles2_idx` (`Articles_idArticles1` ASC, `Articles_url1` ASC) VISIBLE,
  INDEX `fk_Articles_has_Articles_Articles1_idx` (`Articles_idArticles` ASC, `Articles_url` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Articles_Articles1`
    FOREIGN KEY (`Articles_idArticles` , `Articles_url`)
    REFERENCES `mydb`.`Articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Articles_Articles2`
    FOREIGN KEY (`Articles_idArticles1` , `Articles_url1`)
    REFERENCES `mydb`.`Articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Authors` (
  `Articles_idArticles` INT NOT NULL,
  `Articles_url` VARCHAR(200) NOT NULL,
  `Authors_id` INT NOT NULL,
  `Authors_Articles_idArticles` INT NOT NULL,
  `Authors_Articles_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `Articles_url`, `Authors_id`, `Authors_Articles_idArticles`, `Authors_Articles_url`),
  INDEX `fk_Articles_has_Authors_Authors1_idx` (`Authors_id` ASC, `Authors_Articles_idArticles` ASC, `Authors_Articles_url` ASC) VISIBLE,
  INDEX `fk_Articles_has_Authors_Articles1_idx` (`Articles_idArticles` ASC, `Articles_url` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Authors_Articles1`
    FOREIGN KEY (`Articles_idArticles` , `Articles_url`)
    REFERENCES `mydb`.`Articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Authors_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `mydb`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Related_Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Related_Topics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `link` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Related_Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Related_Topics` (
  `Articles_idArticles` INT NOT NULL,
  `Related_Topics_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Articles_has_Related_Topics_Related_Topics1_idx` (`Related_Topics_id` ASC) VISIBLE,
  INDEX `fk_Articles_has_Related_Topics_Articles1_idx` (`Articles_idArticles` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Articles_has_Related_Topics_Articles1`
    FOREIGN KEY (`Articles_idArticles`)
    REFERENCES `mydb`.`Articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Related_Topics_Related_Topics1`
    FOREIGN KEY (`Related_Topics_id`)
    REFERENCES `mydb`.`Related_Topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
