-- MySQL Script generated by MySQL Workbench
-- Sat Mar 13 00:20:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`texts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`texts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_text` MEDIUMTEXT NULL,
  `text` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles` (
  `idArticles` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `image` VARCHAR(200) NULL,
  `Texts_idTexts` INT UNSIGNED NOT NULL,
  `Authors_id` INT UNSIGNED NOT NULL,
  `Sections_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idArticles`, `url`),
  INDEX `fk_Articles_Texts1_idx` (`Texts_idTexts` ASC) VISIBLE,
  INDEX `fk_Articles_Authors1_idx` (`Authors_id` ASC) VISIBLE,
  INDEX `fk_Articles_Sections1_idx` (`Sections_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Texts1`
    FOREIGN KEY (`Texts_idTexts`)
    REFERENCES `mydb`.`texts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `mydb`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Sections1`
    FOREIGN KEY (`Sections_id`)
    REFERENCES `mydb`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Articles` (
  `Articles_idArticles` INT NOT NULL,
  `Articles_url` VARCHAR(200) NOT NULL,
  `Articles_idArticles1` INT NOT NULL,
  `Articles_url1` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `Articles_url`, `Articles_idArticles1`, `Articles_url1`),
  INDEX `fk_Articles_has_Articles_Articles2_idx` (`Articles_idArticles1` ASC, `Articles_url1` ASC) VISIBLE,
  INDEX `fk_Articles_has_Articles_Articles1_idx` (`Articles_idArticles` ASC, `Articles_url` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Articles_Articles1`
    FOREIGN KEY (`Articles_idArticles` , `Articles_url`)
    REFERENCES `mydb`.`articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Articles_Articles2`
    FOREIGN KEY (`Articles_idArticles1` , `Articles_url1`)
    REFERENCES `mydb`.`articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Authors` (
  `Articles_idArticles` INT NOT NULL,
  `Articles_url` VARCHAR(200) NOT NULL,
  `Authors_id` INT NOT NULL,
  `Authors_Articles_idArticles` INT NOT NULL,
  `Authors_Articles_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `Articles_url`, `Authors_id`, `Authors_Articles_idArticles`, `Authors_Articles_url`),
  INDEX `fk_Articles_has_Authors_Authors1_idx` (`Authors_id` ASC, `Authors_Articles_idArticles` ASC, `Authors_Articles_url` ASC) VISIBLE,
  INDEX `fk_Articles_has_Authors_Articles1_idx` (`Articles_idArticles` ASC, `Articles_url` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Authors_Articles1`
    FOREIGN KEY (`Articles_idArticles` , `Articles_url`)
    REFERENCES `mydb`.`articles` (`idArticles` , `url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Authors_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `mydb`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topics=labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topics=labels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `link` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles_to_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles_to_topics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Articles_idArticles` INT NOT NULL,
  `Related_Topics_id` INT NOT NULL,
  INDEX `fk_Articles_has_Related_Topics_Related_Topics1_idx` (`Related_Topics_id` ASC) VISIBLE,
  INDEX `fk_Articles_has_Related_Topics_Articles1_idx` (`Articles_idArticles` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Articles_has_Related_Topics_Articles1`
    FOREIGN KEY (`Articles_idArticles`)
    REFERENCES `mydb`.`articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Related_Topics_Related_Topics1`
    FOREIGN KEY (`Related_Topics_id`)
    REFERENCES `mydb`.`topics=labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linked_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linked_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `link` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles_has_linked_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles_has_linked_articles` (
  `articles_idArticles` INT NOT NULL,
  `articles_url` VARCHAR(200) NOT NULL,
  `articles_Texts_idTexts` INT NOT NULL,
  `articles_Authors_id` INT NOT NULL,
  `articles_Sections_id` INT NOT NULL,
  `linked_articles_idlinked_articles` INT NOT NULL,
  PRIMARY KEY (`articles_idArticles`, `articles_url`, `articles_Texts_idTexts`, `articles_Authors_id`, `articles_Sections_id`, `linked_articles_idlinked_articles`),
  INDEX `fk_articles_has_linked_articles_linked_articles1_idx` (`linked_articles_idlinked_articles` ASC) VISIBLE,
  INDEX `fk_articles_has_linked_articles_articles1_idx` (`articles_idArticles` ASC, `articles_url` ASC, `articles_Texts_idTexts` ASC, `articles_Authors_id` ASC, `articles_Sections_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_linked_articles_articles1`
    FOREIGN KEY (`articles_idArticles` , `articles_url` , `articles_Texts_idTexts` , `articles_Authors_id` , `articles_Sections_id`)
    REFERENCES `mydb`.`articles` (`idArticles` , `url` , `Texts_idTexts` , `Authors_id` , `Sections_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_linked_articles_linked_articles1`
    FOREIGN KEY (`linked_articles_idlinked_articles`)
    REFERENCES `mydb`.`linked_articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles_has_linked_articles1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles_has_linked_articles1` (
  `id` INT NOT NULL,
  `articles_idArticles` INT NOT NULL,
  `linked_articles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `articles_idArticles`, `linked_articles_id`),
  INDEX `fk_articles_has_linked_articles1_linked_articles1_idx` (`linked_articles_id` ASC) VISIBLE,
  INDEX `fk_articles_has_linked_articles1_articles1_idx` (`articles_idArticles` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_linked_articles1_articles1`
    FOREIGN KEY (`articles_idArticles`)
    REFERENCES `mydb`.`articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_linked_articles1_linked_articles1`
    FOREIGN KEY (`linked_articles_id`)
    REFERENCES `mydb`.`linked_articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
